created conspect:
	echo package main > main.go
	type NUL > conspect.md
	go mod init

created makefile:
	type NUL > Makefile

pasted main:# Создать main.go и вписать package main
	echo package main > main.go

created md:
	type NUL > conspect.md

created main.go:
	type NUL > main.go

runProject:# нужен go.mod
	go run .