created conspect:
	echo package main > main.go
	echo  > conspect.md
	go mod init

pasted main:# Создать main.go и вписать package main
	echo package main > main.go

runProject:# нужен go.mod
	go run .